SET IDENTITY_INSERT [dbo].[TYPES_PRODUCT] ON
INSERT INTO [dbo].[TYPES_PRODUCT] ([ID_TYPE_PRODUCT], [NAME_TYPE_PRODUCT], [ID_CATEGORY]) VALUES (1, N'Ноутбук', 1)
INSERT INTO [dbo].[TYPES_PRODUCT] ([ID_TYPE_PRODUCT], [NAME_TYPE_PRODUCT], [ID_CATEGORY]) VALUES (2, N'Носки', 2)
INSERT INTO [dbo].[TYPES_PRODUCT] ([ID_TYPE_PRODUCT], [NAME_TYPE_PRODUCT], [ID_CATEGORY]) VALUES (3, N'Диван', 3)
INSERT INTO [dbo].[TYPES_PRODUCT] ([ID_TYPE_PRODUCT], [NAME_TYPE_PRODUCT], [ID_CATEGORY]) VALUES (4, N'Книга', 4)
INSERT INTO [dbo].[TYPES_PRODUCT] ([ID_TYPE_PRODUCT], [NAME_TYPE_PRODUCT], [ID_CATEGORY]) VALUES (5, N'Кубик-Рубика', 5)
INSERT INTO [dbo].[TYPES_PRODUCT] ([ID_TYPE_PRODUCT], [NAME_TYPE_PRODUCT], [ID_CATEGORY]) VALUES (6, N'Смартфон', 1)
INSERT INTO [dbo].[TYPES_PRODUCT] ([ID_TYPE_PRODUCT], [NAME_TYPE_PRODUCT], [ID_CATEGORY]) VALUES (7, N'Платье', 2)
INSERT INTO [dbo].[TYPES_PRODUCT] ([ID_TYPE_PRODUCT], [NAME_TYPE_PRODUCT], [ID_CATEGORY]) VALUES (8, N'Стол', 3)
SET IDENTITY_INSERT [dbo].[TYPES_PRODUCT] OFF