SET IDENTITY_INSERT [dbo].[ORDER_STATUS] ON
INSERT INTO [dbo].[ORDER_STATUS] ([ID_STATUS], [NAME_STATUS]) VALUES (1, N'В корзине')
INSERT INTO [dbo].[ORDER_STATUS] ([ID_STATUS], [NAME_STATUS]) VALUES (2, N'Не Выдан')
INSERT INTO [dbo].[ORDER_STATUS] ([ID_STATUS], [NAME_STATUS]) VALUES (3, N'Выдан')
SET IDENTITY_INSERT [dbo].[ORDER_STATUS] OFF