SET IDENTITY_INSERT [dbo].[STORES] ON
INSERT INTO [dbo].[STORES] ([ID_STORE], [CITY_STORE], [STREET_STORE], [HOUSE_STORE], [NUMBER_STORE], [RATING_STORE]) VALUES (1, N'Москва', N'Ленинский проспект', N'15', N'1А', 4.5)
INSERT INTO [dbo].[STORES] ([ID_STORE], [CITY_STORE], [STREET_STORE], [HOUSE_STORE], [NUMBER_STORE], [RATING_STORE]) VALUES (2, N'Москва', N'Тверская улица', N'25', N'3', 3.5)
INSERT INTO [dbo].[STORES] ([ID_STORE], [CITY_STORE], [STREET_STORE], [HOUSE_STORE], [NUMBER_STORE], [RATING_STORE]) VALUES (3, N'Москва', N'Садовая-Кудринская улица', N'9', N'12', 3.2)
INSERT INTO [dbo].[STORES] ([ID_STORE], [CITY_STORE], [STREET_STORE], [HOUSE_STORE], [NUMBER_STORE], [RATING_STORE]) VALUES (4, N'Санкт-Петербург', N'Невский проспект', N'100', N'55', 3)
INSERT INTO [dbo].[STORES] ([ID_STORE], [CITY_STORE], [STREET_STORE], [HOUSE_STORE], [NUMBER_STORE], [RATING_STORE]) VALUES (5, N'Казань', N'Баумана улица', N'5', N'24', 4)
SET IDENTITY_INSERT [dbo].[STORES] OFF