SET IDENTITY_INSERT [dbo].[CATEGORIES] ON
INSERT INTO [dbo].[CATEGORIES] ([ID_CATEGORY], [NAME_CATEGORY]) VALUES (1, N'Электроника')
INSERT INTO [dbo].[CATEGORIES] ([ID_CATEGORY], [NAME_CATEGORY]) VALUES (2, N'Одежда')
INSERT INTO [dbo].[CATEGORIES] ([ID_CATEGORY], [NAME_CATEGORY]) VALUES (3, N'Мебель')
INSERT INTO [dbo].[CATEGORIES] ([ID_CATEGORY], [NAME_CATEGORY]) VALUES (4, N'Книги')
INSERT INTO [dbo].[CATEGORIES] ([ID_CATEGORY], [NAME_CATEGORY]) VALUES (5, N'Игрушки')
SET IDENTITY_INSERT [dbo].[CATEGORIES] OFF
